apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-receiver
  namespace: prometheus-stack
spec:
  receivers:
    - name: "null"
    - discordConfigs:
        - avatarURL: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/alertmanager.webp
          username: Alert Manager
          apiURL:
            key: discord-webhook
            name: secrets
      name: discord
  route:
    groupBy:
      - namespace
    groupInterval: 5m
    groupWait: 30s
    receiver: discord
    repeatInterval: 12h
    routes:
      - matchers:
          - name: alertname
            matchType: "=~"
            value: "Watchdog|InfoInhibitor"
        receiver: "null"