{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "secrets",
    "namespace": "prometheus-stack"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "secrets",
        "namespace": "prometheus-stack"
      }
    },
    "encryptedData": {
      "grafana-admin-password": "AgC0nveWRaVxwJq3bZHM83ZdrLQD6xYvsdiabWIEVRT5grNWNAwII3rFY38OUiR2Qjfev8Morl6qXm5rXg0Y8wMXDGP19iEPIpPceNM/IlH70FsaiXGCDG3iRJedhU8mRpQ+1zqADaSsGfydVJLBBmp2YDlgK1+T56jHRrdKZXpfPVUoJzv/K7d7HqdjJv3yKLjh6sAlOPkSWeGWTayACZOrk1Z4/0y6iZ5cmwpkrRdEn2VyGV6Be9ZgMXhesMPxNK3u+bSznd+V7WWT0YRTbT99+0TgM4sT8IJNXhVkXHcmhOGFceDmrWlURscaM4GeIetoG2fpFEbCokdIxr0OEoUsMcMQ5Gb2jSBAZff70K6koWcy0NoHGxnZXkZ7TFYV0f/m6JaBe4hiO1pxRGvPbOMnl50ln/Ev/bQN39Epv+fcb+cKxmuRGeJ8mAXyi37m2N9GdmRrI54k8g/HiR8VcSwAsxnK5ZWb/K1ymJDAtInnEaEHpUylMssadXE04WsoD6aCbgp1Z+MZqrGqJCJmM9Gb4f08yiogQWE2zzAl60J8CkOQyVbUIwS1abWUL33+cj20RihkrtGaZQVhJ6EGp6qRKAUigaNVk+5Eq5Dq7v32LIOeKmOYDZGrUfg96aukg3U4K/1VTYXirdIKwXQTqywg0EsIS8W4sgrT0va0C+Az3OSOwI5AQd7GwVrwHRhRBYifPvkx/Hno55pR3dMf+NGf2e2/Eg==",
      "grafana-admin-user": "AgAZwvXtEPrf8mM/EeyIGcGZ1v3e9r7DzaLItrfLvaa5eOF8ww6NZHqF5uN1AIDmax6ZI1MqraRYZ+yf/a6cZ3WfG35EQwP7D5CoF/CpwQtSdQglXXwDnw2XMNaVl7+1/6vCBJXSuIarJuwoDWQcV3AUq7dIeXCcbkfsG8UZrz6kHR500USZLfGbLHVLtGwJdJuV6shqoXYCqhaB61S/Nnmf4VE2r7rVjlG5Kk5Va05t+nWQpktaCTvEY9tOphoAFLdg6+zDxioOZ+lCM9LUjzCUrkIFJZZ5IhriOIEc5iZoK7I90amf3GnBva50RDbpq1aqiTrniAPva9l5+9EkzItAtSp7kC/3st5odPJG7LsUjBWFoPAjW6jZ+PA0xHwv0v4ybbJ7mty8ncQ50atLO9EKevRlkaZ///iF1Aq6N+JgmNVjktXNyLRZFMEN3OddPzyfK0ipGWC/YkMw1mG68T5cqniqIskCj4Ohh/couKcPavQ1mbfJrAoq6ERAiHAWv/LZYsyA7uxK5sZqHfhYaKH5gEodYbt/zdgJ/CUJe5CJrVQ0dTPuaToQR0Te8feSbDAireyW9CPE4KlIDzhiA3rfLbt9MgqXYKvljD5o3IXqahlixV/BBoLAnS1P/mZdA2wjZTPcrX3B49jKJVkHnbUTjzY9LUmvywMjvakTz2ML7GuKX3PHfcQjuArwNzzzNJ9vRdqv1Q=="
    }
  }
}
