helmCharts:
  - name: mc-router
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 1.5.0
    releaseName: mc-ingress
    namespace: ingress
    valuesFile: values.yaml
resources:
  - resources/networkpolicy.yaml
patches:
  - target:
      kind: Deployment
      name: mc-ingress
    patch: |
      - op: replace
        path: /kind
        value: DaemonSet
      - op: remove
        path: /spec/replicas
      - op: remove
        path: /spec/strategy
    options:
      allowKindChange: true