deschedulerPolicy:
  metricsProviders:
    - source: KubernetesMetrics
  profiles:
    - name: default
      pluginConfig:
        - name: "DefaultEvictor"
          args:
            minPodAge: 600s
            podProtections:
              defaultDisabled:
                - PodsWithLocalStorage
                - DaemonSetPods
                - SystemCriticalPods
        - name: "RemoveFailedPods"
          args:
            excludeOwnerKinds:
              - "Job"
            minPodLifetimeSeconds: 600
        - name: "RemoveFailedPods"
          args:
            minPodLifetimeSeconds: 86400
        - name: "RemovePodsHavingTooManyRestarts"
          args:
            podRestartThreshold: 10
            includingInitContainers: true
      plugins:
        deschedule:
          enabled:
            - "RemoveFailedPods"
            - "RemovePodsHavingTooManyRestarts"
    - name: low-usage
      pluginConfig:
        - name: "DefaultEvictor"
          args:
            podProtections:
              defaultDisabled:
                - PodsWithLocalStorage
              extraEnabled:
                - PodsWithPVC
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 40
              "memory": 40
              "pods": 60
            targetThresholds:
              "cpu" : 75
              "memory": 70
              "pods": 75
            evictionLimits:
              node: 5
      plugins:
        balance:
          enabled:
            - "LowNodeUtilization"