deschedulerPolicy:
  metricsProviders:
    - source: KubernetesMetrics
  profiles:
    - name: default
      pluginConfig:
        - name: "DefaultEvictor"
          args:
            minPodAge: 600s
            podProtections:
              defaultDisabled:
                - PodsWithLocalStorage
                - DaemonSetPods
                - SystemCriticalPods
        - name: "RemoveFailedPods"
          args:
            excludeOwnerKinds:
              - "Job"
            minPodLifetimeSeconds: 600
        - name: "RemoveFailedPods"
          args:
            minPodLifetimeSeconds: 86400

      plugins:
        deschedule:
          enabled:
            - "RemoveFailedPods"
    - name: low-usage
      pluginConfig:
        - name: "DefaultEvictor"
          args:
            podProtections:
              defaultDisabled:
                - PodsWithLocalStorage
              extraEnabled:
                - PodsWithPVC
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 40
              "memory": 40
              "pods": 40
            targetThresholds:
              "cpu" : 60
              "memory": 60
              "pods": 60
            evictionLimits:
              node: 5
      plugins:
        balance:
          enabled:
            - "LowNodeUtilization"