apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: xonotic
  namespace: xonotic
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: xonotic
      k8s:app.kubernetes.io/instance: xonotic
  ingress:
    - toPorts:
        - ports:
            - protocol: UDP
              port: "26000"
