apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: engiqueers
  namespace: ingress
  annotations:
    cert-manager.io/issuer: le-dns-engiqueers
spec:
  gatewayClassName: cilium
  listeners:
    - name: engiqueers-tls
      hostname: "engiqueersconcordia.ca"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.engiqueers/access-engiqueers: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - name: engiqueers-tls
    - name: engiqueers-tls-passthrough
      protocol: TLS
      port: 443
      hostname: "engiqueersconcordia.ca"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.engiqueers/access-engiqueers: "true"
    - name: engiqueers-sub-tls
      hostname: "*.engiqueersconcordia.ca"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.engiqueers/access-engiqueers: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - name: engiqueers-tls
    - name: engiqueers-sub-tls-passthrough
      protocol: TLS
      port: 443
      hostname: "*.engiqueersconcordia.ca"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.engiqueers/access-engiqueers: "true"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: engiqueers-insecure
  namespace: ingress
spec:
  gatewayClassName: cilium
  listeners:
    - name: engiqueers
      port: 80
      protocol: HTTP
      hostname: "engiqueersconcordia.ca"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.engiqueers/access-engiqueers-insecure: "true"

    - name: engiqueers-sub
      port: 80
      protocol: HTTP
      hostname: "*.engiqueersconcordia.ca"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.engiqueers/access-engiqueers-insecure: "true"
