apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: engiqueers
  namespace: ingress
spec:
  gatewayClassName: cilium
  listeners:
    - name: engiqueers-tls
      hostname: "engiqueersconcordia.ca"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"
      tls:
        mode: Terminate
        certificateRefs:
          - name: engiqueers-tls
    - name: engiqueers-sub-tls
      hostname: "*.engiqueersconcordia.ca"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"
      tls:
        mode: Terminate
        certificateRefs:
          - name: engiqueers-tls
    - name: engiqueers-migration-tls
      hostname: "engiqueers.ecaconcordia.ca"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"
      tls:
        mode: Terminate
        certificateRefs:
          - name: engiqueers-migration-tls
    - name: engiqueers-ldaps
      hostname: "ldaps.engiqueersconcordia.ca"
      port: 636
      protocol: TLS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"
      tls:
        mode: Terminate
        certificateRefs:
          - name: engiqueers-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: engiqueers-insecure
  namespace: ingress
spec:
  gatewayClassName: cilium
  listeners:
    - name: engiqueers
      port: 80
      protocol: HTTP
      hostname: "engiqueersconcordia.ca"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"

    - name: engiqueers-sub
      port: 80
      protocol: HTTP
      hostname: "*.engiqueersconcordia.ca"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"

    - name: engiqueers-migration
      port: 80
      protocol: HTTP
      hostname: "engiqueers.ecaconcordia.ca"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              policy.engiqueers/domain: "internal"