apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    gateway.engiqueers/access-engiqueers: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    gateway.engiqueers/access-engiqueers: "true"
    gateway.engiqueers/access-engiqueers-insecure: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
kind: Namespace
apiVersion: v1
metadata:
  name: cnpg-system
---
kind: Namespace
apiVersion: v1
metadata:
  name: authentik
  labels:
    gateway.engiqueers/access-engiqueers: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: headlamp
  labels:
    gateway.engiqueers/access-engiqueers: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: test-mc
  labels:
    gateway.engiqueers/access-engiqueers: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: harbor
  labels:
    gateway.engiqueers/access-engiqueers: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: website
  labels:
    gateway.engiqueers/access-engiqueers: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: cdi
  labels:
    gateway.engiqueers/access-engiqueers: "true"
    cdi.kubevirt.io: ''
---
kind: Namespace
apiVersion: v1
metadata:
  name: kubevirt
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kubevirt.io: ''
---
kind: Namespace
apiVersion: v1
metadata:
  name: user-juan
