apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    access-gateway-engiqueers: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    access-gateway-engiqueers: "true"
    access-gateway-engiqueers-insecure: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
kind: Namespace
apiVersion: v1
metadata:
  name: test
