apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-lvm
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  storage: "lvm"
  volgroup: "openebs"
  fsType: "xfs"
  shared: "yes"
  thinProvision: "yes"
allowVolumeExpansion: true
mountOptions:
  - discard
reclaimPolicy: Delete
provisioner: local.csi.openebs.io
allowedTopologies:
  - matchLabelExpressions:
      - key: is-storage-node
        values:
          - "true"
