helmCharts:
  - name: headlamp
    repo: https://kubernetes-sigs.github.io/headlamp/
    version: 0.45.0
    releaseName: headlamp
    namespace: headlamp
    valuesFile: values.yaml
resources:
  - resources/secrets.yaml