config:
  oidc:
    secret:
      create: false

    externalSecret:
      enabled: true
      name: headlamp-secrets
      hasScopes: true

httpRoute:
  enabled: true
  hostnames:
    - headlamp.engiqueersconcordia.ca
  parentRefs:
    - name: engiqueers
      namespace: ingress

