apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "host-policy"
spec:
  nodeSelector: {}
  ingress:
    - fromEntities:
        - remote-node
        - host
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
            - port: "50000"
              protocol: TCP
            - port: "51820"
              protocol: UDP
    # Let metrics-server scrape the kubelet
    - toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
      fromEndpoints:
        - matchLabels:
            k8s:k8s-app: metrics-server
            k8s:io.kubernetes.pod.namespace: kube-system
    - toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
      fromEndpoints:
        - matchLabels:
            k8s:k8s-app: hubble-relay
            k8s:io.kubernetes.pod.namespace: kube-system
    - icmps:
        - fields:
            - type: EchoRequest
              family: IPv4
