apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - ingress
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all-to-ingress
spec:
  endpointSelector:
    matchExpressions:
      - key: reserved:ingress
        operator: Exists
  ingress:
    - fromEntities:
        - all
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-kubedns
specs:
  - endpointSelector:
      matchLabels:
        k8s:k8s-app: kube-dns
        k8s:io.kubernetes.pod.namespace: kube-system
    ingress:
      - toPorts:
          - ports:
              - port: "53"
                protocol: "ANY"
        fromEntities:
          - cluster
  - endpointSelector: {}
    egress:
      - toPorts:
          - ports:
              - port: "53"
                protocol: "ANY"
            rules:
              dns:
                - matchPattern: "*"
        toEndpoints:
          - matchLabels:
              k8s:k8s-app: kube-dns
              k8s:io.kubernetes.pod.namespace: kube-system
      - toPorts:
          - ports:
              - port: "53"
                protocol: "ANY"
            rules:
              dns:
                - matchPattern: "*"
        toEntities:
          - world
    enableDefaultDeny:
      egress: false
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: isolate-egress
specs:
  - endpointSelector:
      matchExpressions:
        - key: k8s:netpol.engiqueers/egress-mode
          operator: In
          values:
            - Isolate
    egressDeny:
      - toEntities:
          - all
  - endpointSelector:
      matchExpressions:
        - key: k8s:io.cilium.k8s.namespace.labels.netpol.engiqueers/egress-mode
          operator: In
          values:
            - Isolate
    egressDeny:
      - toEntities:
          - all
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: unrestricted-egress
specs:
  - endpointSelector:
      matchExpressions:
        - key: k8s:netpol.engiqueers/egress-mode
          operator: In
          values:
            - Unrestricted
        - key: k8s:io.cilium.k8s.namespace.labels.netpol.engiqueers/allow-unrestricted-egress
          operator: In
          values:
            - "true"
    egress:
      - toEntities:
          - all
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "default-egress"
specs:
  - endpointSelector: {}
    egress:
      - toEntities:
          - kube-apiserver
      - toEndpoints:
          - {}
      - toCIDRSet:
          - cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble-ui
  ingress:
  - ports:
    - port: http
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-system-internal
  namespace: kube-system
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-cilium-health"
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      "reserved:health": ""
  ingress:
    - fromEntities:
        - host
        - remote-node