apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vivado
  namespace: user-juan
spec:
  preference:
    kind: VirtualMachineClusterPreference
    name: ubuntu
  runStrategy: Always
  template:
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
          interfaces:
            - name: k8s
              masquerade: {}
              ports:
                - port: 22
        cpu:
          sockets: 1
          cores: 6
          threads: 1
        memory:
          guest: 12G
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
      networks:
        - name: k8s
          pod: { }
      volumes:
        - dataVolume:
            name: vivado
          name: vivado