namespace: loki
helmCharts:
  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    version: 18.12.1
    releaseName: loki
    namespace: loki
    valuesFile: values.yaml
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.11.1
    releaseName: alloy
    namespace: loki
    valuesFile: values-alloy.yaml

resources:
  - resources/alloy-netpol.yaml
  - resources/secrets.yaml
