namespace: loki
helmCharts:
  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    version: 18.7.1
    releaseName: loki
    namespace: loki
    valuesFile: values.yaml
resources:
  - resources/secrets.yaml