serviceMonitor:
  enabled: true

alloy:
  mounts:
    varlog: false
  configMap:
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }
      
      livedebugging {
        enabled = true
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      discovery.relabel "pods" {
        targets    = discovery.kubernetes.pods.targets
      
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_node_name"]
          target_label  = "node_name"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          target_label  = "app"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_ip"]
          target_label  = "pod_ip"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod_name"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.process.process.receiver]
      }
      
      loki.source.kubernetes_events "events" {
        forward_to = [loki.process.process.receiver]
      }
      
      loki.process "process" {
        forward_to = [loki.write.endpoint.receiver]
        
        // Extract log level from json or logfmt
        stage.json {
          expressions = { 
            level = "",
          }
        }
        stage.logfmt {
          mapping = {
            "level" = "",
          }
        }
      
        // Lowercase the extracted value
        stage.template {
            source   = "level"
            template = "{{ "{{" }} ToLower .Value {{ "}}" }}"
        }
      
        // Set a default value for the level label
        stage.static_labels {
          values = {
            level = "unknown",
          }
        }
        
        // Fill in the level label with the level extracted value
        stage.labels {
          values = {
            level  = "",
          }
        }
      
        // Log level based on http status code
        stage.match {
          selector = "{status=~\"[123][0-9][0-9]\"}"
          stage.static_labels {
            values = { level = "info" }
          }
        }
        stage.match {
          selector = "{status=~\"[4][0-9][0-9]\"}"
          stage.static_labels {
            values = { level = "warning" }
          }
        }
        stage.match {
          selector = "{status=~\"[5][0-9][0-9]\"}"
          stage.static_labels {
            values = { level = "error" }
          }
        }
      
        // Normalize log levels
        stage.match {
          selector = "{level=\"dbg\"}"
          stage.static_labels {
            values = { level = "debug" }
          }
        }
        stage.match {
          selector = "{level=\"inf\"}"
          stage.static_labels {
            values = { level = "info" }
          }
        }
        stage.match {
          selector = "{level=~\"(warn|wrn)\"}"
          stage.static_labels {
            values = { level = "warning" }
          }
        }
        stage.match {
          selector = "{level=\"err\"}"
          stage.static_labels {
            values = { level = "error" }
          }
        }
        
        // Drop high cardinality labels to structured metadata
        stage.structured_metadata {
          values = {
            instance = "",
          }
          regex = "pod_.*"   // Adds all extracted values starting with 'pod_' to structured metadata.
        }
      }

      loki.write "endpoint" {
        endpoint {
            url = "http://loki-gateway:80/loki/api/v1/push"
            tenant_id = "local"
        }
      }