loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  rulerConfig:
    enable_api: true
  storage:
    type: none
  auth_enabled: false

deploymentMode: Monolithic

singleBinary:
  replicas: 1

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

networkPolicy:
  enabled: true
  metrics:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: prometheus-stack
  ingress:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: prometheus-stack

gateway:
  route:
    main:
      enabled: false
      hostname: loki.engiqueersconcordia.ca
      parentRefs:
        - name: engiqueers
          namespace: ingress

  basicAuth:
    enabled: false
    existingSecret: secrets

  nginxConfig:
    logFormat: |-
      main escape=json '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"request_method":"$request_method",'
        '"request_uri":"$request_uri",'
        '"status":"$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"request_time":"$request_time",'
        '"http_referrer":"$http_referer",'
        '"http_user_agent":"$http_user_agent",'
        '"http_x_forwarded_for":"$http_x_forwarded_for"'
      '}';

monitoring:
  dashboards:
    enabled: true

  rules:
    enabled: true

  alerts:
    enabled: true

  serviceMonitor:
    enabled: true


