crds:
  enabled: true

enableCertificateOwnerRef: true

prometheus:
  enabled: true
  servicemonitor:
    enabled: true

config:
  enableGatewayAPI: true
  acmeDNS01Config:
    recursiveNameserversOnly: true
    recursiveNameservers:
      - 8.8.8.8:53
      - 1.1.1.1:53

networkPolicy:
  enabled: true

webhook:
  networkPolicy:
    enabled: true

cainjector:
  networkPolicy:
    enabled: true