apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespaces.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
  - resources/gateway.yaml
  - resources/https-redirect.yaml
  - resources/crb-admin.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Delete=confirm,Prune=confirm
    target:
      version: v1
      kind: Namespace