resources:
  # TODO: add update check hooks
  # KubeVirt
  # When updating, check if kubevirt.yaml needs to be updated as well (https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml)
  - https://github.com/kubevirt/kubevirt/releases/download/v1.9.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.9.0/kubevirt-network-policies.yaml
  - resources/kubevirt.yaml


  # CDI
  # Manually downloaded so we can remove v1alpha1 from it. For some reason the controller removes it automatically but then argo tries to bring it back
  #- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.65.0/cdi-operator.yaml
  - resources/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.66.0/network-policies.yaml
  - resources/cdi.yaml
  - resources/storageprofile.yaml
  - resources/networkpolicy.yaml

patches:
  - target:
      kind: Namespace
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: namespace