resources:
  # KubeVirt
  # When updating, check if kubevirt.yaml needs to be updated as well (https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml)
  - https://github.com/kubevirt/kubevirt/releases/download/v1.8.2/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.8.2/kubevirt-network-policies.yaml
  - resources/kubevirt.yaml

  # CDI
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.65.0/cdi-operator.yaml
#  - resources/cdi.yaml