helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts
    version: 1.19.4
    releaseName: cilium
    namespace: kube-system
    valuesInline:
      preflight:
        enabled: true
      agent: false
      operator:
        enabled: false
    apiVersions:
      - gateway.networking.k8s.io/v1/GatewayClass