namespace: authentik
helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2026.8.0
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml
resources:
  - resources/cluster.yaml
  - resources/networkpolicy.yaml
  - resources/refgrant.yaml
  - resources/secrets.yaml
