global:
  domain: argocd-diff.engiqueersconcordia.ca

  networkPolicy:
    create: true
    defaultDenyIngress: true

configs:
  cm:
    accounts.gha-diff-bot: apiKey

    kustomize.buildOptions: --enable-helm
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_GRPCRoute: |
      jqPathExpressions:
      - '.spec.rules[].backendRefs[].group'
      - '.spec.rules[].backendRefs[].kind'
      - '.spec.rules[].backendRefs[].weight'
      - '.spec.parentRefs[].group'
      - '.spec.parentRefs[].kind'
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_HTTPRoute: |
      jqPathExpressions:
      - '.spec.rules[].backendRefs[].group'
      - '.spec.rules[].backendRefs[].kind'
      - '.spec.rules[].backendRefs[].weight'
      - '.spec.parentRefs[].group'
      - '.spec.parentRefs[].kind'
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_Gateway: |
      jqPathExpressions:
      - '.spec.listeners[].tls.certificateRefs[].group'
      - '.spec.listeners[].tls.certificateRefs[].kind'
  secret:
    createSecret: false
  params:
    server.insecure: "true"
    applicationsetcontroller.enable.new.git.file.globbing: "true"
  rbac:
    policy.csv: |
      g, gha-diff-bot, role:admin

redisSecretInit:
  enabled: false

server:
  service:
    # Enable gRPC over HTTP/2
    servicePortHttpsAppProtocol: kubernetes.io/h2c

  httproute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd-diff.engiqueersconcordia.ca
  grpcroute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd-diff-api.engiqueersconcordia.ca
    rules:
      - {}

notifications:
  enabled: false

createClusterRoles: false
crds:
  install: false
dex:
  enabled: false
applicationSet:
  replicas: 0
controller:
  roleRules:
    - apiGroups:
        - "*"
      resources:
        - "*"
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - argoproj.io
      resources:
        - applications
        - applications/status
      verbs:
        - get
        - list
        - watch
        - update
        - patch