namespace: openebs
helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    version: 4.4.0
    releaseName: openebs
    namespace: openebs
    valuesFile: values.yaml
resources:
  - resources/storageclass.yaml
# Remove this when https://github.com/kubernetes-sigs/kustomize/issues/6058 is fixed
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: openebs
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: openebs
    target:
      kind: DaemonSet
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: openebs
    target:
      kind: Service
