namespace: nextcloud
helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 9.2.6
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: values.yaml
  - name: redis
    repo: oci://registry-1.docker.io/cloudpirates
    version: 0.34.23
    releaseName: redis
    namespace: nextcloud
    valuesFile: values-redis.yaml
resources:
  - resources/euro-office/deployment.yaml
  - resources/euro-office/netpol.yaml
  - resources/euro-office/pvc.yaml
  - resources/euro-office/service.yaml
  - resources/rclone/cronjob.yaml
  - resources/rclone/pvc.yaml
  - resources/whiteboard/deployment.yaml
  - resources/whiteboard/netpol.yaml
  - resources/whiteboard/service.yaml
  - resources/cluster.yaml
  - resources/httproute.yaml
  - resources/netpol.yaml
  - resources/secrets.yaml
images:
  - name: ghcr.io/nextcloud-releases/whiteboard
    newTag: v1.5.9@sha256:b60b7633f90d106ac6922f9bc27e1a1ca2442488b740fefdae4c812f34e9cebc
  - name: ghcr.io/euro-office/documentserver
    newTag: v9.3.3@sha256:6068075cc247f9283d337b2cf9a105d9df49fcd8cd6b5e82fa90640df1552e80