global:
  security:
    allowInsecureImages: false

httpRoute:
  enabled: true
  hostnames:
    - nextcloud.engiqueersconcordia.ca
  parentRefs:
    - name: engiqueers
      namespace: ingress

nextcloud:
  host: nextcloud.engiqueersconcordia.ca
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
  configs:
    proxy.config.php: |-
      <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
      'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql

  existingSecret:
    enabled: true
    secretName: nextcloud-db-app
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: dbname

externalRedis:
  enabled: true
  host: "redis"
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    passwordKey: redis-password

cronjob:
  enabled: ture

persistence:
  enabled: true
  size: 50Gi

imaginary:
  enabled: true

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 300000
  successThreshold: 1