global:
  security:
    allowInsecureImages: false

httpRoute:
  enabled: false
  hostnames:
    - nc.engiqueersconcordia.ca
  parentRefs:
    - name: engiqueers
      namespace: ingress

nextcloud:
  host: nc.engiqueersconcordia.ca
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
  configs:
    proxy.config.php: |-
      <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
      'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
  phpconfigs:
    perf.ini: |-
      pm = dynamic
      pm.max_children = 30
      pm.start_servers = 8
      pm.min_spare_servers = 4
      pm.max_spare_servers = 16
      pm.max_requests = 500
      opcache.jit = 1255
      opcache.jit_buffer_size = 8M

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql

  existingSecret:
    enabled: true
    secretName: nextcloud-db-app
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: dbname

externalRedis:
  enabled: true
  host: "redis"
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    passwordKey: redis-password

cronjob:
  enabled: ture

persistence:
  enabled: true
  size: 50Gi

imaginary:
  enabled: true

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 300000
  successThreshold: 1

image:
  flavor: fpm

nginx:
  enabled: true