apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jupyterhub-db
  namespace: jupyterhub
spec:
  enablePDB: false
  instances: 1

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      secret:
        name: