apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-diff-gha-bot
  namespace: argocd-diff
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-diff-gha-bot
  namespace: argocd-diff
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-diff-gha-bot
  namespace: argocd-diff
subjects:
  - kind: ServiceAccount
    name: argocd-diff-gha-bot
    namespace: argocd-diff
roleRef:
  kind: Role
  name: argocd-diff-gha-bot
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-diff-gha-bot
  annotations:
    kubernetes.io/service-account.name: argocd-diff-gha-bot
type: kubernetes.io/service-account-token