apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kubeapi
  namespace: kubevirt
specs:
  - endpointSelector:
      matchLabels:
        kubevirt.io: virt-api
    ingress:
      - toPorts:
          - ports:
              - port: "8443"
                protocol: TCP
        fromEntities:
          - cluster
  - endpointSelector:
      matchLabels:
        kubevirt.io: virt-operator
    ingress:
      - toPorts:
          - ports:
              - port: "8444"
                protocol: TCP
        fromEntities:
          - cluster