helmCharts:
  - name: cert-manager-webhook-ovh
    repo: https://aureq.github.io/cert-manager-webhook-ovh
    version: 0.9.16
    releaseName: cert-manager-webhook-ovh
    namespace: ingress
    valuesFile: values.yaml
resources:
  - resources/ovh-creds.yaml
  - resources/networkpolicy.yaml