helmCharts:
  - name: minecraft
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 5.1.3
    releaseName: test-mc
    namespace: test-mc
    valuesFile: values.yaml
  - name: mc-router
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 1.5.0
    releaseName: test-mc-router
    namespace: test-mc
    valuesFile: values-router.yaml
resources:
  - resources/secrets.yaml
  - resources/config.yaml
  - resources/networkpolicy.yaml
patches:
  - target:
      kind: Deployment
      name: test-mc-router
    patch: |
      - op: replace
        path: /kind
        value: DaemonSet
      - op: remove
        path: /spec/replicas
      - op: remove
        path: /spec/strategy
    options:
      allowKindChange: true