helmCharts:
  - name: minecraft
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 5.1.3
    releaseName: test-mc
    namespace: test-mc
    valuesFile: values.yaml
  # TODO: remove rcon
  - name: rcon-web-admin
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 1.2.1
    releaseName: test-mc-rcon
    namespace: test-mc
    valuesFile: values-rcon.yaml
resources:
  - resources/secrets.yaml
  - resources/config.yaml
  - resources/netpol.yaml