resources:
  requests:
    memory: 4Gi

minecraftServer:
  eula: "TRUE"
  version: "1.21.1"
  type: "NEOFORGE"
  ops: "alexkar598"
  gameMode: "creative"
  motd: "EngiQueers Test Server"

  memory: 4G
  rcon:
    enabled: true
    withGeneratedPassword: true

workloadAsStatefulSet: true
strategyType: RollingUpdate
serviceAnnotations:
  "mc-router.itzg.me/externalServerName": "testmc.engiqueersconcordia.ca"

extraVolumes:
  - volumes:
      - configMap:
          name: test-mc-config
          defaultMode: 0777
        name: config
    volumeMounts:
      - mountPath: /config
        name: config
        readOnly: true

extraEnv:
  USES_PROXY_PROTOCOL: "1"
  LOAD_ENV_FROM_FILE: /config/startup.sh
  GENERIC_PACK: "https://iris.alexkar598.dev/static/modpack.zip"
  GENERIC_PACKS_DISABLE_MODS: |
    sodium-neoforge-0.8.13+mc1.21.1.jar
    sodium-extra-neoforge-0.9.3+mc1.21.1.jar