minecraftServer:
  eula: "TRUE"
  version: "26.1.2"
  type: "PAPER"
  ops: "alexkar598"
  gameMode: "creative"
  motd: "EngiQueers Test Server"

  rcon:
    enabled: true
    existingSecret: "test-mc-secrets"

workloadAsStatefulSet: true
strategyType: RollingUpdate
serviceAnnotations:
  "mc-router.itzg.me/externalServerName": "testmc.engiqueersconcordia.ca"
podLabels:
  allow-mc-router: "true"

extraVolumes:
  - volumes:
      - configMap:
          name: test-mc-config
          defaultMode: 0777
        name: config
    volumeMounts:
      - mountPath: /config/paper-global.yaml
        name: config
        readOnly: true
        subPath: paper-global.yaml