helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.28.2
    releaseName: cnpg
    namespace: cnpg-system
    valuesFile: values.yaml
resources:
  - resources/networkpolicy.yaml