helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: 87.16.1
    releaseName: prometheus-stack
    namespace: prometheus-stack
    valuesFile: values.yaml
resources:
  - resources/secrets.yaml