crds:
  upgradeJob:
    enabled: false

alertmanager:
  networkPolicy:
    enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-lvm
    alertmanagerConfigMatcherStrategy:
       type: OnNamespaceExceptForAlertmanagerNamespace

  route:
    main:
      enabled: true

      hostnames:
        - "alertmanager.engiqueersconcordia.ca"
      parentRefs:
        - name: engiqueers
          namespace: ingress

      filters:
        - externalAuth:
            backendRef:
              name: authentik-server
              namespace: authentik
              port: 9000
            protocol: HTTP
            http:
              path: /outpost.goauthentik.io/auth/envoy
              allowedHeaders:
                - cookie
              allowedResponseHeaders:
                - set-cookie

defaultRules:
  disabled:
    # We can't really do anything about it. This warns us that if a node fails,
    # the other(s) may not be able to take the full load
    KubeMemoryOvercommit: true
    KubeCPUOvercommit: true

kubeProxy:
  # Cilium replaces kubeproxy
  enabled: false

grafana:
  admin:
    existingSecret: "secrets"
    userKey: grafana-admin-user
    passwordKey: grafana-admin-password

  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 15Gi
    storageClassName: local-lvm

  extraSecretMounts:
     - name: secret-files
       mountPath: /etc/secrets
       secretName: secrets
       readOnly: true
       optional: false
       subPath: ""

  grafana.ini:
      server:
        root_url: https://grafana.engiqueersconcordia.ca

      auth:
        disable_login_form: true

      auth.basic:
        enabled: false

      auth.generic_oauth:
        enabled: true
        client_id: "$__file{/etc/secrets/oidc-client-id}"
        client_secret: "$__file{/etc/secrets/oidc-client-secret}"
        auth_url: "https://auth.engiqueersconcordia.ca/application/o/authorize/"
        token_url: "https://auth.engiqueersconcordia.ca/application/o/token/"
        scopes: "openid profile grafana_role offline_access email"
        allow_sign_up: true
        auto_login: true
        login_attribute_path: preferred_username
        name_attribute_path: name
        email_attribute_path: email
        role_attribute_path: grafana_role
        role_attribute_strict: true
        allow_assign_grafana_admin: true
        use_pkce: true
        use_refresh_token: true
        validate_id_token: true
        jwk_set_url: "https://auth.engiqueersconcordia.ca/application/o/grafana/jwks/"

  route:
    main:
      enabled: true
      hostnames:
        - "grafana.engiqueersconcordia.ca"
      parentRefs:
        - name: engiqueers
          namespace: ingress

prometheusOperator:
  admissionWebhooks:
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
    mutatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync
    validatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync
    patch:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded

  networkPolicy:
    enabled: true
    flavor: cilium

prometheus:
  networkPolicy:
    enabled: true
    flavor: cilium
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-lvm
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

    retention: 30d

    ruleNamespaceSelector:
      matchLabels:
        policy.engiqueers/domain: "internal"
    ruleSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector:
      matchLabels:
        policy.engiqueers/domain: "internal"
    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorNamespaceSelector:
      matchLabels:
        policy.engiqueers/domain: "internal"
    podMonitorSelectorNilUsesHelmValues: false

    probeNamespaceSelector:
      matchLabels:
        policy.engiqueers/domain: "internal"
    probeSelectorNilUsesHelmValues: false

    scrapeConfigNamespaceSelector:
      matchLabels:
        policy.engiqueers/domain: "internal"
    scrapeConfigSelectorNilUsesHelmValues: false


cleanPrometheusOperatorObjectNames: true