helmCharts:
  - name: minecraft
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 5.2.0
    releaseName: modded-mc
    namespace: modded-mc
    valuesFile: values.yaml
resources:
  - resources/config.yaml
