namespace: rustfs
helmCharts:
  - name: rustfs
    repo: https://charts.rustfs.com
    version: "1.0.0"
    releaseName: rustfs
    namespace: rustfs
    valuesFile: values.yaml
resources:
  - resources/httproute.yaml
  - resources/secrets.yaml