replicaCount: 1

drivesPerNode: 1

mode:
  standalone:
    enabled: true
  distributed:
    enabled: false

secret:
  existingSecret: secrets

ingress:
  enabled: false

gatewayApi:
  enabled: false

storageClass:
  name: local-lvm
  dataStorageSize: 30Gi
  logStorageSize: 5Gi

config:
  rustfs:
    obs_environment: "production"