apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-internal
  namespace: harbor
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress
