namespace: website
helmCharts:
  - name: website
    version: 0.1.0
    releaseName: website
    namespace: website

images:
  - name: harbor.engiqueersconcordia.ca/website/website
    digest: sha256:8e831222facc8d76525ff85c9cb91046759562e34ed4682ad167039982f35f56

helmGlobals:
  chartHome: local-charts

resources:
  - resources/redirect-route.yaml
  - resources/migration-route.yaml