namespace: website
helmCharts:
  - name: website
    version: 0.1.0
    releaseName: website
    namespace: website

images:
  - name: harbor.engiqueersconcordia.ca/website/website
    digest: sha256:ab840159159bb21e88a32bf6354e47be264a79c474a70ac87f3b9eeeefd0de6f

helmGlobals:
  chartHome: local-charts

resources:
  - resources/redirect-route.yaml
  - resources/migration-route.yaml