apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/targetRevision
  syncPolicy:
    applicationsSync: create-update
  generators:
    - git:
        repoURL: https://github.com/EngiQueersConcordia/infrastructure.git
        revision: HEAD
        files:
          - path: apps/*/config.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
        argocd-diff-preview/watch-pattern: '{{.path.path}}/.*'
    spec:
      project: "default"
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
      source:
        repoURL: https://github.com/EngiQueersConcordia/infrastructure.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: in-cluster
  templatePatch: |- 
    spec:
      syncPolicy:
        automated:
          enabled: {{ (hasKey . "autoSync") | ternary (index . "autoSync") true | toJson }}
          prune: {{ (hasKey . "prune") | ternary (index . "prune") true | toJson }}
          selfHeal: {{ (hasKey . "selfHeal") | ternary (index . "selfHeal") true | toJson }}
          allowEmpty: false
      destination:
          namespace: {{ (hasKey . "namespace") | ternary (index . "namespace") nil | toJson }}