apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-update
  generators:
    - git:
        repoURL: https://codeberg.org/EngiQueers-Concordia/infrastructure.git
        revision: HEAD
        files:
          - path: apps/*/config.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
      source:
        repoURL: https://codeberg.org/EngiQueers-Concordia/infrastructure.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        kustomize:
          components:
            - ../common
      destination:
        name: in-cluster
  templatePatch: |- 
    spec:
      syncPolicy:
        automated:
          enabled: {{ (hasKey . "autoSync") | ternary (index . "autoSync") true | toJson }}
          prune: {{ (hasKey . "prune") | ternary (index . "prune") true | toJson }}
          selfHeal: {{ (hasKey . "selfHeal") | ternary (index . "selfHeal") true | toJson }}
          allowEmpty: false
