apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-update
  generators:
    - git:
        repoURL: https://codeberg.org/EngiQueers-Concordia/infrastructure.git
        revision: HEAD
        files:
          - path: apps/*/config.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        gen: 1
    spec:
      project: "default"
      source:
        repoURL: https://codeberg.org/EngiQueers-Concordia/infrastructure.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: in-cluster
  templatePatch: |- 
    spec:
      syncPolicy:
        automated:
          enabled: {{ or (index . "autoSync") true | toJson }}
          prune: {{ or (index . "prune") false | toJson }}
          selfHeal: {{ or (index . "selfHeal") false | toJson }}
          allowEmpty: false
