{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "argocd-secret",
    "namespace": "argocd"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "argocd-secret",
        "namespace": "argocd",
        "annotations": {
          "sealedsecrets.bitnami.com/patch": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "webhook.github.secret": "AgAHX5bu6JIAfYAXjj8DQjkDQw/5gp1h+ezD5IUM5J+D/ByWpoFtm60u6kZKeTxeCl/LvIICJuQVBjEnvH0NvlKWC49GYQrjBZxTwxk1x3oJ3vERuVKUeOs82FeVZXZ65NhVjQvjNGwboBSHKLpPGFHXI9MgIbG8hJNcj1zeJei92M4CEfNljoZTFX0hIQIcDvD1mpP7SEk1nsNwdLL0cThfHm+FqIN7g4FAyhCKt0rnU3uNEEJdI7xVhxOwZx7SSSpsNic/zs+BzFzLCh7gyFiRsHD4Wl7dxcWbU5zLbX3YUJagbMFBf9CAxzxgVyH735F7jFqYMAOSFmHBM9X52x7/VTfu0XCX5zt+wmejVlpjR7ozdGEn5s17Qy4W2hCZyv4+LVgo1vib2cBzXBFrNJ3fpxkBdj2fs1kbD8w+wL2yoxDPVEfumZeYcriKKrjHuWpgmivtQbepdvN9x801aPTUPCptsBZsRtW5pSDGkdGai401taptoAen0KNq4kBPVgymq2TOmqeDySc2OnCaGg4m9jph1IfUVGEEa2OSOOFWs2eNtBVIa1OaVf0n6BODkkT8ug+zlDVy68EYqcgyfbC4b4dEO7bw1QpfIn4H7QT2hRNknYravEpn+IzwQ8UCjyxwQLOwRKp1YBfNxgHvBzQ8js525zkzVoQ/U8+8d7dxUB4i50jW+Sq6YYSkYT/tYJW3FDFQ45JB5LUhPrdT8qoEkH7hBQ==",
      "webhook.gogs.secret": "AgCk8MBnsO5SV6RRKkZA74LQOt7diuUSPpT21ZwyYnd4z4TBsnYKV7jJ5oxoCoDS7WqYn1rv/F74bwaGx/zTgPHUAInGLB2ts9W+dkvFFjtkLAVqz2MeX3zP0iPQI8gDF93X/13RV2n31uUfJChkYspyqbvoG+Hur6kYGCMlAk+Ga6wAxbDpSV3/HNGd/QbmBb7BnBz4R77lVguCo3wDDK85SjmwULOTA7LplNvqNj1dGR4Ktm14OpuSHnz2ucDtpVNjIOPWhV3uYY5e9+vq6xHYw85Tu3boblBrWwptWsWxfYTVk8aNwagv/te5ZpwE/FNn7sDFvckMAwk4R31mkeaQsQqxH0+rdbPAAsCU2xLHavBVy//coI7iZgqoKpnvI3n/zJf3MtTv+gA14HUEU4EM2K6wP3gVCM2QFKM9fZ2KbZyacUpWJdyLQ/7EnQxjZURMazaR3F/Q3gT4WAhiS2qSRLZHswUpw9TxBj3o0K9eC2+FhsU27PleNV6vRAQmTSm9wBNJzyxiC6dGlN/s7YwSysvoGCwYIn9Xy69F5D310cLm+Hn77xFULJsO7cZxaSJ8Yed39EcQR6jdl0ZIr2n86/OGubbtBTLJ2ZrRVDR1L4hW0SsrNaGDXUvx58cCvieKU161fQujWXXPQvI21zeW1cctSZcnLDFd+h9FWl1xNuiTJEcZKH8wKSTi7f8BWfFrXimJitoBWIM1QDKWSbdRRSPKWw=="
    }
  }
}
