{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "argocd-redis",
    "namespace": "argocd"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "argocd-redis",
        "namespace": "argocd"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "auth": "AgAh+8+Cmxw0nffHzsctGQGZyt4UOHvb8g4zJpSZUyOb0Uizu0RETA7GnD0vJ8Tyo8J9hXSLaTNk8TwabvzFseWU4LmVnSpdSWaY8zL7l6mlR4F+8SlnYQcLZLbl/bozREfhdpY+fywOjX9TxeDngOXbkB+H/u8bE6Xz6ogdzJQ+oWON6cZF0ZuzuD2eKpCEpjQnTsi8f/pqvd6qZ6eCEzttM7za0mcmqwKSO4o8Fss9c0Ujh1G756IeVZvteBBi/K/gbNL3SIkm5WuGfZsPYBZQ77sWUFJwE7NHSmQu27yN58471ayuNUEA+x/MogIgKVWi4QJE2P1ftkIHgiOUwSbR4O8p9kszkuFl9NFAj9hU9w7MHpkeVvmr4Hb1k7GL4OgycjPoexr6Yfbv4ou/gYeAjri92MDwUvjxgP5WP8kYPLWYZ8lcFipMfFJtfXGyEognFdroP7TYS+LjxALrVVVCJoLV4n+cq7X6YbOOkM4WNhPdSrG0ziLjuwjV/X4UCMDksWFNXLDqWYGW1xNLUOMvOmLfZOPvBz308KFDsYdKnyJtfVwr6M62doA2QpRjVK+UGOtUhPSG0k0EqMNmH6ShVdYEqikyOPCXoHjPvjuEOJa2fehHaesKw0btpLbxYVZbf+ztMjnM6QI4hkya0qYArat9ouO52iJhZJGPKCgxHd8tGOJju44+YYBZIzlSgIsZRcJPyaOTFbM9OWJfQrQH"
    }
  }
}
