{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "argocd-secret",
    "namespace": "argocd"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "argocd-secret",
        "namespace": "argocd",
        "annotations": {
          "sealedsecrets.bitnami.com/patch": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "webhook.github.secret": "AgBE2q0fnK+6HNgmdq9QDxNaMhnUyJWFEBROQS15xal8RN7/SnOQ/lc+A/jehnI8mLmbZPdW4WDomOMlr3CeQfCo1IHbkOwi55ETefX9eeIO/PGAvU9Fb1IZqlQ/4aMFJer1T81MAJsahr69T4TY9xRmTCC+PSMr7t8QEHbtO520XpMtuyRvlNAK6R4lFZ0ZWrD0FQOYD9NP3Pajl6nvN5g3veUs5H/y5Tm2VmZmMd2866EDGI5pwhAln3lo1HzaesqUy2sxZix3HBRrT5dx+HnhUc4Z/IZO1dxsjxeayKNszYxEainKCouhG1zzf//xkmxpjsPl0fH8DL9tFAAd6HY68MIyg1Gmw5/9LNOL7gExF9CVU/i+3fXF4a3zbMrrBP/fLkFhK5TS1ownPVvYic8BoP4OaDSR6uICIHdvzhsgh7xe82wh3o42G2I0Vu+fLnJN3ajx/NyLOHjfWwHNyRtpMOQQdCsLPReKzYXvB0mDeQAhAHx2KKsfxZpm2fACauf8t5YoRQRMKeSmGWA5h7w48SqeckkE91XIs2qfIQe2pedKqwJ5WZcxliBwGUGOwBDbe+Wr1/4e/RCBVNJWGYumvlDl7ARmjuR2Lj7UXJDWs0/diSq6BRTbJj6mM9mztF7cN9SZ4vEenK9to4of8Q/h+7xy3uciUvtDiUr44Wu9ceGPg9A2XzuJ+DMVp5DNQ0MjudUW7ccHckTuGGNnXvYBGmTgaA=="
    }
  }
}
