apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-bridge
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: webhook-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: webhook-bridge
    spec:
      containers:
      - name: wekhook-bridge
        image: harbor.engiqueersconcordia.ca/webhook-bridge/webhook-bridge@sha256:24cc2163fa44739af11281d682fa6b13135e28a26eb9add47c2d624fcae6bce5
        imagePullPolicy: IfNotPresent
        env:
          - name: ARGOCD_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                key: webhook.github.secret
                name: argocd-secret
          - name: ARGOCD_WEBHOOK_URL
            value: "http://argocd-applicationset-controller.argocd.svc:7000/"
        ports:
        - containerPort: 8080
          name: webhook
          protocol: TCP
