namespace: stakater
helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 2.2.16
    releaseName: stakater
    namespace: stakater
    valuesFile: values.yaml
