namespace: xonotic
resources:
  - resources/configmap.yaml
  - resources/netpol.yaml
  - resources/pvc.yaml
  - resources/secrets.yaml
  - resources/service.yaml
  - resources/statefulset.yaml
images:
  - name: harbor.engiqueersconcordia.ca/xonotic/xonotic
    digest: sha256:67300fea666199807ad1eeb39aca67f753227f3ee33a0e8de1d78e2850a573f7
