name: Comment on new PR
on:
  pull_request_target:
    types:
      - opened
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Post Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr comment $PR_NUMBER --body-file - << EOF
          To deploy this PR to production, run the following command:
          \`\`\`bash
          script/override_app.sh $PR_NUMBER <appname> 
          \`\`\`
          
          To reset <appname>, run the following command:
          \`\`\`bash
          script/override_app.sh <appname> 
          \`\`\`
          EOF