namespace: argocd
helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 9.5.14
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
resources:
  - resources/secrets.yaml
  - resources/webhook-bridge/deployment.yaml
  - resources/webhook-bridge/httproute.yaml
  - resources/webhook-bridge/networkpolicy.yaml
  - resources/webhook-bridge/service.yaml
  - resources/applicationset.yaml
