helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 9.5.14
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
resources:
  - ./secrets.yaml
  - ./webhook-bridge/deployment.yaml
  - ./webhook-bridge/httproute.yaml
  - ./webhook-bridge/service.yaml
