namespace: argocd
helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 10.4.0
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
    apiVersions:
      - monitoring.coreos.com/v1
resources:
  - resources/secrets.yaml
  - resources/webhook-bridge/deployment.yaml
  - resources/webhook-bridge/httproute.yaml
  - resources/webhook-bridge/networkpolicy.yaml
  - resources/webhook-bridge/service.yaml
  - resources/applicationset.yaml
patches:
  - target:
      kind: GRPCRoute
      name: argocd-server-grpc
    patch: |
      - op: replace
        path: /spec/rules/0/backendRefs/0/port
        value: 443
