global:
  domain: argocd.engiqueersconcordia.ca

  networkPolicy:
    create: true
    defaultDenyIngress: true

configs:
  cm:
    admin.enabled: false
    exec.enabled: true
    kustomize.buildOptions: --enable-helm
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_GRPCRoute: |
      jqPathExpressions:
      - '.spec.rules[].backendRefs[].group'
      - '.spec.rules[].backendRefs[].kind'
      - '.spec.rules[].backendRefs[].weight'
      - '.spec.parentRefs[].group'
      - '.spec.parentRefs[].kind'
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_HTTPRoute: |
      jqPathExpressions:
      - '.spec.rules[].backendRefs[].group'
      - '.spec.rules[].backendRefs[].kind'
      - '.spec.rules[].backendRefs[].weight'
      - '.spec.parentRefs[].group'
      - '.spec.parentRefs[].kind'
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_Gateway: |
      jqPathExpressions:
      - '.spec.listeners[].tls.certificateRefs[].group'
      - '.spec.listeners[].tls.certificateRefs[].kind'

    dex.config: |
      connectors:
      - type: oidc
        id: oidc
        name: OIDC
        config:
          issuer: https://auth.engiqueersconcordia.ca/application/o/argo-cd/
      
          clientID: $OIDC_CLIENT_ID
          clientSecret: $OIDC_CLIENT_SECRET
      
          insecureSkipEmailVerified: true
      
          insecureEnableGroups: true
      
          userIDKey: sub
          userNameKey: name
  secret:
    createSecret: false
  params:
    server.insecure: "true"
    applicationsetcontroller.enable.new.git.file.globbing: "true"
  rbac:
    policy.csv: |
      g, argocd-admin, role:admin

dex:
  env:
    - name: OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: argocd-secret
          key: oidc_client_id
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argocd-secret
          key: oidc_client_secret



  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  service:
    # Enable gRPC over HTTP/2
    servicePortHttpsAppProtocol: kubernetes.io/h2c

  httproute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca
  grpcroute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd-api.engiqueersconcordia.ca
    rules:
      - {}

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  httproute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca
    rules:
      - filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replaceFullPath: /api/webhook
              type: ReplaceFullPath
        matches:
        - path:
            type: PathPrefix
            value: /api/applicationset-webhook



notifications:
  enabled: false

controller:
  metrics:
    enabled: true
    applicationLabels:
      enabled: true
    serviceMonitor:
      enabled: true
    rules:
      enabled: true
      spec:
       - alert: ArgoAppMissing
         expr: |
           absent(argocd_app_info) == 1
         for: 15m
         labels:
           severity: critical
         annotations:
           summary: "[Argo CD] No reported applications"
           description: >
             Argo CD has not reported any applications data for the past 15 minutes which
             means that it must be down or not functioning properly.  This needs to be
             resolved for this cloud to continue to maintain state.
       - alert: ArgoAppNotSynced
         expr: |
           argocd_app_info{sync_status!="Synced"} == 1
         for: 12h
         labels:
           severity: warning
         annotations:
           summary: "[{{ $labels.name }}] Application not synchronized"
           description: >
             The application {{ $labels.name }} has not been synchronized for over
             12 hours which means that the state of this cloud has drifted away from the
             state inside Git.

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

