global:
  domain: argocd.engiqueersconcordia.ca

  networkPolicy:
    create: true
    defaultDenyIngress: true

configs:
  cm:
    admin.enabled: false
    exec.enabled: true
    kustomize.buildOptions: --enable-helm
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_GRPCRoute: |
      jqPathExpressions:
      - '.spec.rules[].backendRefs[].group'
      - '.spec.rules[].backendRefs[].kind'
      - '.spec.rules[].backendRefs[].weight'
      - '.spec.parentRefs[].group'
      - '.spec.parentRefs[].kind'
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_HTTPRoute: |
      jqPathExpressions:
      - '.spec.rules[].backendRefs[].group'
      - '.spec.rules[].backendRefs[].kind'
      - '.spec.rules[].backendRefs[].weight'
      - '.spec.parentRefs[].group'
      - '.spec.parentRefs[].kind'
    resource.customizations.ignoreDifferences.gateway.networking.k8s.io_Gateway: |
      jqPathExpressions:
      - '.spec.listeners[].tls.certificateRefs[].group'
      - '.spec.listeners[].tls.certificateRefs[].kind'

    dex.config: |
      connectors:
      - type: oidc
        id: oidc
        name: OIDC
        config:
          issuer: https://auth.engiqueersconcordia.ca/application/o/argo-cd/
      
          clientID: $OIDC_CLIENT_ID
          clientSecret: $OIDC_CLIENT_SECRET
      
          insecureSkipEmailVerified: true
      
          insecureEnableGroups: true
      
          userIDKey: sub
          userNameKey: name
  secret:
    createSecret: false
  params:
    server.insecure: "true"
    applicationsetcontroller.enable.new.git.file.globbing: "true"
  rbac:
    policy.csv: |
      g, argocd-admin, role:admin

dex:
  env:
    - name: OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: argocd-secret
          key: oidc_client_id
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argocd-secret
          key: oidc_client_secret


server:
  service:
    # Enable gRPC over HTTP/2
    servicePortHttpsAppProtocol: kubernetes.io/h2c

  httproute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca
  grpcroute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca
    rules:
      - {}

notifications:
  enabled: false
