global:
  domain: argocd.engiqueersconcordia.ca

configs:
  cm:
    exec.enabled: true
    kustomize.buildOptions: --enable-helm
  secret:
    createSecret: false
  params:
    server.insecure: "true"
    applicationsetcontroller.enable.new.git.file.globbing: "true"

server:
  httproute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca
  grpcroute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca
    rules:
      - {}

applicationSet:
  httproute:
    enabled: true
    parentRefs:
      - name: engiqueers
        namespace: ingress
    hostnames:
      - argocd.engiqueersconcordia.ca

notifications:
  enabled: false
